# Generated by Django 4.0.1 on 2022-01-20 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_alter_document_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_editors',
            field=models.ManyToManyField(blank=True, related_name='current_editing_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
